title: Alexander Oakley
author: Alexander Oakley
description: About me and some things I find interesting.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
# theme: jekyll-theme-minimal