title: Alexander Oakley
author: Alexander Oakley
description: A site about me and some of the things I find interesting.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
# theme: jekyll-theme-minimal